# Set a plain language title for the site.
title: GitHub for no-coders

# Write a short description for the site. This is used for "meta description."
description: An exploration of the features and benefits of GitHub for no-code uses

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Enable for live hosting on GitHub Pages
baseurl: /ghfnc-preso

# Remove generation of additional style.css
theme: null

collections:
  slides:
    output: true